export const platformy = ["PC", "PlayStation", "Xbox", "Nintendo Switch"];

export const Gry = [
  {
    id: 1,
    nazwa: "Wiedzmin 3",
    platformy: "PC",
    rok: 2015,
    ocena: 10,
    ukonczona: true,
  },
  {
    id: 2,
    nazwa: "Cyberpunk 2077",
    platformy: "PC",
    rok: 2020,
    ocena: 8,
    ukonczona: false,
  },
  {
    id: 3,
    nazwa: "Mario Kart 8",
    platformy: "Nintendo Switch",
    rok: 2017,
    ocena: 9,
    ukonczona: true,
  },
  {
    id: 4,
    nazwa: "The Last of Us Part II",
    platformy: "PlayStation 4",
    rok: 2020,
    ocena: 10,
    ukonczona: true,
  },
  {
    id: 5,
    nazwa: "Halo Infinite",
    platformy: "Xbox",
    rok: 2021,
    ocena: 7,
    ukonczona: false,
  },
  {
    id: 6,
    nazwa: "God of War",
    platformy: "PlayStation 4",
    rok: 2018,
    ocena: 10,
    ukonczona: true,
  },
  {
    id: 7,
    nazwa: "The Legend of Zelda: Breath of the Wild",
    platformy: "Nintendo Switch",
    rok: 2017,
    ocena: 10,
    ukonczona: true,
  },
  {
    id: 8,
    nazwa: "Forza Horizon 5",
    platformy: "Xbox",
    rok: 2021,
    ocena: 9,
    ukonczona: false,
  },
  {
    id: 9,
    nazwa: "Red Dead Redemption 2",
    platformy: "PC",
    rok: 2018,
    ocena: 10,
    ukonczona: true,
  },
  {
    id: 10,
    nazwa: "Spider-Man: Miles Morales",
    platformy: "PlayStation 5",
    rok: 2020,
    ocena: 9,
    ukonczona: true,
  },
  {
    id: 11,
    nazwa: "Super Smash Bros. Ultimate",
    platformy: "Nintendo Switch",
    rok: 2018,
    ocena: 10,
    ukonczona: false,
  },
  {
    id: 12,
    nazwa: "Elden Ring",
    platformy: "PC",
    rok: 2019,
    ocena: 8,
    ukonczona: true,
  },
];
